# Generated by Django 5.2.15 on 2026-07-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitcheck', '0037_filter_enforce_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitsubmission',
            name='hidden_at',
            field=models.DateTimeField(blank=True, default=None, help_text="Set when the pilot removes this submission from their own history view. Hides the row from the owner's Pilot Fittings list only - reviewers, reports, and Secure Groups compliance still see it.", null=True),
        ),
    ]
