# Generated by Django 5.2.15 on 2026-07-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitcheck', '0038_fitsubmission_hidden_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctrine',
            name='auto_approve',
            field=models.CharField(choices=[('OFF', 'Off'), ('C', 'Compliant only'), ('CS', 'Compliant or with substitutions')], default='OFF', help_text="Automatically approve inventory-validated (ESI) submissions graded against this doctrine whose verdict meets the chosen tier. Never applies to pasted fits, which can't be tied to a real hull. Off = every submission waits for a human reviewer.", max_length=3),
        ),
        migrations.AlterField(
            model_name='submissionactionlog',
            name='action',
            field=models.CharField(choices=[('SUB', 'Submitted'), ('CHK', 'Auto-checked'), ('RCK', 'Re-checked'), ('APP', 'Approved'), ('AAP', 'Auto-approved'), ('REJ', 'Rejected'), ('COM', 'Commented')], max_length=3),
        ),
    ]
