# Generated by Django 5.2.15 on 2026-07-08 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitcheck', '0039_doctrine_auto_approve_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_reviewers_new_submission', models.BooleanField(default=True, help_text='Ping everyone with review authority as soon as a member submits a fit for review. Has no effect while Reviewer digest (below) is on.')),
                ('reviewer_digest', models.BooleanField(default=False, help_text='Send a periodic summary of the pending queue instead of a ping per submission. Suppresses the per-submission ping above; requires fitcheck.tasks.send_review_digest to be scheduled via CELERYBEAT_SCHEDULE to actually run.')),
                ('notify_member_decision', models.BooleanField(default=True, help_text="Tell a pilot their submission was approved or rejected - covers both a human reviewer's decision and a doctrine's automatic 'approved by rule' decision.")),
                ('notify_pilots_stale', models.BooleanField(default=True, help_text='Tell a pilot when a fitting-standard change re-grades their pending submission (with an old-to-new module diff when the BOM changed), and warn holders of an already-approved submission that the fit has moved on since their approval.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification settings',
                'verbose_name_plural': 'Notification settings',
            },
        ),
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mute_all', models.BooleanField(default=False, help_text='Suppress every Fit Check notification for this account.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fitcheck_notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification preference',
                'verbose_name_plural': 'Notification preferences',
            },
        ),
    ]
