# Generated by Django 5.2.15 on 2026-07-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('fitcheck', '0040_notificationsettings_usernotificationpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctrinecategory',
            name='reviewer_groups',
            field=models.ManyToManyField(blank=True, help_text='Members of these Auth groups who ALSO hold a Fit Check review permission may review submissions for doctrines in this category. Empty = any reviewer may review it. This grants REVIEW AUTHORITY and is distinct from the visibility groups above (which control who may SEE the category).', related_name='+', to='auth.group'),
        ),
    ]
